MentorConnect/MentorConnect/Models/Mentor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MentorConnect.Models
{
    public class Mentor
    {
        public string _imagePath { get; set; }
        public int _id { get; set; }
        public string _userName { get; set; }
        public string major { get; set; }
        public ICollection<subject> subjects { get; set; }
        public string description { get; set; }

        public string ListSubjects {
            get { 
                string list = "";
                foreach(subject sub in subjects)
                {
                    list += sub.name + ", ";
                }
                return list.TrimEnd(' ').TrimEnd(',');
            }
        }
    }
}

MentorConnect/MentorConnect/Controllers/MentorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MentorConnect.Models;
using MentorConnect.Core;

namespace MentorConnect.Controllers
{
    public class MentorController : Controller
    {
        //
        // GET: /MentorHome/
        CoreMentorHome ch = new CoreMentorHome();
        public ActionResult Index()
        {
            string username = System.Web.HttpContext.Current.Session["username"] as String;
            ViewBag.userfname = System.Web.HttpContext.Current.Session["fname"] as String;
            List<MentorshipRequest> msrList = ch.FindAllBriefRequests(username);
            MentorRequestsModel mrm = new MentorRequestsModel();
            mrm._allrequests = msrList;
            return View(mrm);
        }
        public ActionResult DisplayRequestDetail(int mshipID)
        {
            MentorScheduleModel msm = ch.FindthisScheduleRequest(mshipID);
            return View("EachScheduleRequest", msm);
        }
        public ActionResult DisplayMentorshipDetail(int mshipID)
        {
            MentorScheduleModel msm = ch.FindthisMentorshipSchedule(mshipID);
            return View("WeeklySchedule", msm);
        }
        public ActionResult EditProfile()
        {
            ViewBag.userfname = System.Web.HttpContext.Current.Session["fname"] as String;
            string username = System.Web.HttpContext.Current.Session["username"] as String;
            MentorScheduleModel msm = ch.FindMentorSchedule(username);
            return View("EditMentorSchedule", msm);
        }

        public ActionResult UpdateMentorProfile(MentorScheduleModel msm)
        {
            if(ch.UpdateMentorProfile(msm) > 0)
                return RedirectToAction("Index");
            else
                return View("EditMentorSchedule", msm);
        }

        public ActionResult GetAllMentorships()
        {
            string username = System.Web.HttpContext.Current.Session["username"] as String;
            ViewBag.userfname = TempData["fname"];
            MentorshipList mshList = ch.GetAllMentorships(username);
            return View("MentorshipList", mshList);
        }

        public ActionResult StartMentorship(int mshipid)
        {
            ViewBag.userfname = System.Web.HttpContext.Current.Session["fname"] as String;            
            VideoConference vc = ch.GetVideoConference(mshipid);
            return View("Mentorship",vc);
        }

        public void AcceptScheduleRespose(int mid, int stuid, int subid, int mshipid)
        {
            ch.AcceptScheduleResponse(mid,stuid,subid,mshipid);
        }
        public void RejectScheduleRespose(int mid, int stuid, int subid, int mshipid)
        {
            ch.RejectScheduleResponse(mid, stuid, subid, mshipid);
        }
    }
}

MentorConnect/MentorConnect/Views/Mentor/EachScheduleRequest.cshtml
@model MentorConnect.Models.MentorScheduleModel
@using MentorConnect.Models

@{
    ViewBag.Title = "Schedule Request";
    Layout = null;
    bool isClashing = false;
}
@Styles.Render("~/Content/MentorScheduleDialog")
@Scripts.Render("~/bundles/mentorSchedule")
<div>
    <div class="mtrDetails_d">
        <table class="mtrDetailsTbl_d">
            <tr>
                <td>Student Name: @Model.name </td>
                <td>Subject: @Model.subjectName @Html.HiddenFor(m => m.subject, new { id = "subId" })</td>
            </tr>
            <tr>
                <td>Comment: @Model.comment</td>
                <td></td>
            </tr>
        </table>
    </div>
    <div class="mtrImg_d">
        <img src="@Model.imgpath" />
    </div>
    @Html.HiddenFor(m => m._mentorId, new { id = "mid" })
    @Html.HiddenFor(m => m.studentId, new { id = "sid" })
    @Html.HiddenFor(m => m.mentorShipID, new { id = "mshipid" })
</div>


<div class="tblSch_d">
    <div>
        <span class="schTitle_d">Schedule Requested</span>
        <div class="key2_d"></div>Requested
        <div class="key3_d"></div>Conflicts with your schedule
    </div>
    <table class="scheduleTable_d">
        <tr><th></th><th>10:00 AM</th><th>11:00 AM</th><th>12:00 PM</th><th>1:00 PM</th><th>02:00 PM</th><th>03:00 PM</th><th>04:00 PM</th><th>05:00 PM</th><th>06:00 PM</th><th>07:00 PM</th><th>08:00 PM</th><th>09:00 PM</th><th>10:00 PM</th></tr>
        <tr>
            <td>Sun</td>
            @for (int i = 0; i < Model._schedule[0]._timeandRequest.Count; i++)
            {
                if (Model._schedule[0]._timeandRequest[i].isRequested == 0)
                {
                    <td><input type="button" class="notAvailBtn_d" /></td>
                }
                else if (Model._schedule[0]._timeandRequest[i].isClashing)
                {
                    isClashing = true;
                    <td><input type="button" class="clashBtn_d" /></td>
                }
                else
                {
                    <td><input type="button" class="SelectedBtn_d" /></td>
                }

            }
        </tr>
        <tr>
            <td>Mon</td>
            @for (int i = 0; i < Model._schedule[1]._timeandRequest.Count; i++)
            {
                if (Model._schedule[1]._timeandRequest[i].isRequested == 0)
                {
                    <td><input type="button" class="notAvailBtn_d" /></td>
                }
                else if (Model._schedule[1]._timeandRequest[i].isClashing)
                {
                    isClashing = true;
                    <td><input type="button" class="clashBtn_d" /></td>
                }
                else
                {
                    <td><input type="button" class="SelectedBtn_d" /></td>
                }

            }
        </tr>
        <tr>
            <td>Tue</td>
            @for (int i = 0; i < Model._schedule[2]._timeandRequest.Count; i++)
            {
                if (Model._schedule[2]._timeandRequest[i].isRequested == 0)
                {
                    <td><input type="button" class="notAvailBtn_d" /></td>
                }
                else if (Model._schedule[2]._timeandRequest[i].isClashing)
                {
                    isClashing = true;
                    <td><input type="button" class="clashBtn_d" /></td>
                }
                else
                {
                    <td><input type="button" class="SelectedBtn_d" /></td>
                }

            }
        </tr>
        <tr>
            <td>Wed</td>
            @for (int i = 0; i < Model._schedule[3]._timeandRequest.Count; i++)
            {
                if (Model._schedule[3]._timeandRequest[i].isRequested == 0)
                {
                    <td><input type="button" class="notAvailBtn_d" /></td>
                }
                else if (Model._schedule[3]._timeandRequest[i].isClashing)
                {
                    isClashing = true;
                    <td><input type="button" class="clashBtn_d" /></td>
                }
                else
                {
                    <td><input type="button" class="SelectedBtn_d" /></td>
                }

            }
        </tr>
        <tr>
            <td>Thu</td>
            @for (int i = 0; i < Model._schedule[4]._timeandRequest.Count; i++)
            {
                if (Model._schedule[4]._timeandRequest[i].isRequested == 0)
                {
                    <td><input type="button" class="notAvailBtn_d" /></td>
                }
                else if (Model._schedule[4]._timeandRequest[i].isClashing)
                {
                    isClashing = true;
                    <td><input type="button" class="clashBtn_d" /></td>
                }
                else
                {
                    <td><input type="button" class="SelectedBtn_d" /></td>
                }

            }
        </tr>
        <tr>
            <td>Fri</td>
            @for (int i = 0; i < Model._schedule[5]._timeandRequest.Count; i++)
            {
                if (Model._schedule[5]._timeandRequest[i].isRequested == 0)
                {
                    <td><input type="button" class="notAvailBtn_d" /></td>
                }
                else if (Model._schedule[5]._timeandRequest[i].isClashing)
                {
                    isClashing = true;
                    <td><input type="button" class="clashBtn_d" /></td>
                }
                else
                {
                    <td><input type="button" class="SelectedBtn_d" /></td>
                }

            }
        </tr>
        <tr>
            <td>Sat </td>
            @for (int i = 0; i < Model._schedule[6]._timeandRequest.Count; i++)
            {
                if (Model._schedule[6]._timeandRequest[i].isRequested == 0)
                {
                    <td><input type="button" class="notAvailBtn_d" /></td>
                }
                else if (Model._schedule[6]._timeandRequest[i].isClashing)
                {
                    isClashing = true;
                    <td><input type="button" class="clashBtn_d" /></td>
                }
                else
                {
                    <td><input type="button" class="SelectedBtn_d" /></td>
                }

            }
        </tr>
    </table>
</div>

<div class="footDiv">
    <div class="reqBtnDiv_d">
        @if (!isClashing)
        {
            <input type="submit" value="Accept Mentorship" class="requestButton_d" onclick="AcceptScheduleResponse(@Model._mentorId, @Model.studentId, @Model.subject, @Model.mentorShipID)" />
        }
        else
        {
            <input type="submit" value="Accept Mentorship" class="requestButton_d" disabled />
        }
    </div>
    <div class="reqBtnDiv_d">
        <input type="submit" value="Reject Mentorship" class="requestButton_d" onclick="RejectScheduleResponse(@Model._mentorId, @Model.studentId, @Model.subject, @Model.mentorShipID)" />
    </div>
</div>

MentorConnect/MentorConnect/Views/Mentor/EditMentorSchedule.cshtml
@model MentorConnect.Models.MentorScheduleModel
@using MentorConnect.Models

@{
    ViewBag.Title = "Edit Mentor Schedule";
    Layout = null;
}
@Styles.Render("~/Content/MentorSchedule")
@Scripts.Render("~/bundles/editmentorSchedule")
@using (Html.BeginForm("UpdateMentorProfile", "Mentor", FormMethod.Post))
{
    <div>

        <div class="mtrDetails">
            <table class="mtrDetailsTbl">
                <tr>
                    <td>Name: @Model.name @Html.HiddenFor(m => m.name)</td>
                    <td>Subject: @Html.DropDownListFor(m => m.subject, Model._subjects)</td>
                </tr>
                <tr>
                    <td>Major: @Html.TextBoxFor(m => m.major)</td>
                    <td></td>
                </tr>
            </table>
        </div>
        <div class="mtrImg">
            <img src="@Model.imgpath" />
            @Html.HiddenFor(m => m.imgpath)
        </div>
        @Html.HiddenFor(m => m._mentorId)
        @Html.HiddenFor(m => m.studentId)
    </div>


    <div class="tblSch">
        <div>
            <span class="schTitle">Mentor Schedule</span>
            <div class="key1"></div>Available
        </div>
        <table class="scheduleTable">
            <tr><th></th><th>10:00 AM</th><th>11:00 AM</th><th>12:00 PM</th><th>1:00 PM</th><th>02:00 PM</th><th>03:00 PM</th><th>04:00 PM</th><th>05:00 PM</th><th>06:00 PM</th><th>07:00 PM</th><th>08:00 PM</th><th>09:00 PM</th><th>10:00 PM</th></tr>
            <tr>
                <td>Sun @Html.HiddenFor(m => m._schedule[0].day)</td>
                @for (int i = 0; i < Model._schedule[0]._timeandRequest.Count; i++)
                {
                    string newID = "1_" + Model._schedule[0]._timeandRequest[i].timeId.ToString();
                    string newIDBtn = newID + "_btn";
                    if (Model._schedule[0]._timeandRequest[i].isMentorAvailable == 0)
                    {
                        <td><input type="button" class="notAvailBtn" onclick="toggleButton('@newID')" id="@newIDBtn" /></td>
                    }
                    else
                    {
                        <td><input type="button" class="AvailBtn" id="@newIDBtn" /></td>
                    }

                    @Html.HiddenFor(m => m._schedule[0]._timeandRequest[i].timeId)
                    @Html.HiddenFor(m => m._schedule[0]._timeandRequest[i].isMentorAvailable, new { id = newID })

                }
            </tr>
            <tr>
                <td>Mon @Html.HiddenFor(m => m._schedule[1].day)</td>
                @for (int i = 0; i < Model._schedule[1]._timeandRequest.Count; i++)
                {
                    string newID = "2_" + Model._schedule[1]._timeandRequest[i].timeId.ToString();
                    string newIDBtn = newID + "_btn";
                    if (Model._schedule[1]._timeandRequest[i].isMentorAvailable == 0)
                    {
                        <td><input type="button" class="notAvailBtn" onclick="toggleButton('@newID')" id="@newIDBtn" /></td>
                    }
                    else
                    {
                        <td><input type="button" class="AvailBtn" id="@newIDBtn" /></td>
                    }

                    @Html.HiddenFor(m => m._schedule[1]._timeandRequest[i].timeId)
                    @Html.HiddenFor(m => m._schedule[1]._timeandRequest[i].isMentorAvailable, new { id = newID })

                }
            </tr>
            <tr>
                <td>Tue @Html.HiddenFor(m => m._schedule[2].day)</td>
                @for (int i = 0; i < Model._schedule[2]._timeandRequest.Count; i++)
                {
                    string newID = "3_" + Model._schedule[2]._timeandRequest[i].timeId.ToString();
                    string newIDBtn = newID + "_btn";
                    if (Model._schedule[2]._timeandRequest[i].isMentorAvailable == 0)
                    {
                        <td><input type="button" class="notAvailBtn" onclick="toggleButton('@newID')" id="@newIDBtn" /></td>
                    }
                    else
                    {
                        <td><input type="button" class="AvailBtn" id="@newIDBtn" /></td>
                    }

                    @Html.HiddenFor(m => m._schedule[2]._timeandRequest[i].timeId)
                    @Html.HiddenFor(m => m._schedule[2]._timeandRequest[i].isMentorAvailable, new { id = newID })

                }
            </tr>
            <tr>
                <td>Wed @Html.HiddenFor(m => m._schedule[3].day)</td>
                @for (int i = 0; i < Model._schedule[3]._timeandRequest.Count; i++)
                {
                    string newID = "4_" + Model._schedule[3]._timeandRequest[i].timeId.ToString();
                    string newIDBtn = newID + "_btn";
                    if (Model._schedule[3]._timeandRequest[i].isMentorAvailable == 0)
                    {
                        <td><input type="button" class="notAvailBtn" onclick="toggleButton('@newID')" id="@newIDBtn" /></td>
                    }
                    else
                    {
                        <td><input type="button" class="AvailBtn" id="@newIDBtn" /></td>
                    }

                    @Html.HiddenFor(m => m._schedule[3]._timeandRequest[i].timeId)
                    @Html.HiddenFor(m => m._schedule[3]._timeandRequest[i].isMentorAvailable, new { id = newID })

                }
            </tr>
            <tr>
                <td>Thu @Html.HiddenFor(m => m._schedule[4].day)</td>
                @for (int i = 0; i < Model._schedule[4]._timeandRequest.Count; i++)
                {
                    string newID = "5_" + Model._schedule[4]._timeandRequest[i].timeId.ToString();
                    string newIDBtn = newID + "_btn";
                    if (Model._schedule[4]._timeandRequest[i].isMentorAvailable == 0)
                    {
                        <td><input type="button" class="notAvailBtn" onclick="toggleButton('@newID')" id="@newIDBtn" /></td>
                    }
                    else
                    {
                        <td><input type="button" class="AvailBtn" id="@newIDBtn" /></td>
                    }

                    @Html.HiddenFor(m => m._schedule[4]._timeandRequest[i].timeId)
                    @Html.HiddenFor(m => m._schedule[4]._timeandRequest[i].isMentorAvailable, new { id = newID })

                }
            </tr>
            <tr>
                <td>Fri @Html.HiddenFor(m => m._schedule[5].day)</td>
                @for (int i = 0; i < Model._schedule[5]._timeandRequest.Count; i++)
                {
                    string newID = "6_" + Model._schedule[5]._timeandRequest[i].timeId.ToString();
                    string newIDBtn = newID + "_btn";
                    if (Model._schedule[5]._timeandRequest[i].isMentorAvailable == 0)
                    {
                        <td><input type="button" class="notAvailBtn" onclick="toggleButton('@newID')" id="@newIDBtn" /></td>
                    }
                    else
                    {
                        <td><input type="button" class="AvailBtn" id="@newIDBtn" /></td>
                    }

                    @Html.HiddenFor(m => m._schedule[5]._timeandRequest[i].timeId)
                    @Html.HiddenFor(m => m._schedule[5]._timeandRequest[i].isMentorAvailable, new { id = newID })

                }
            </tr>
            <tr>
                <td>Sat @Html.HiddenFor(m => m._schedule[6].day)</td>
                @for (int i = 0; i < Model._schedule[6]._timeandRequest.Count; i++)
                {
                    string newID = "7_" + Model._schedule[6]._timeandRequest[i].timeId.ToString();
                    string newIDBtn = newID + "_btn";
                    if (Model._schedule[6]._timeandRequest[i].isMentorAvailable == 0)
                    {
                        <td><input type="button" class="notAvailBtn" onclick="toggleButton('@newID')" id="@newIDBtn" /></td>
                    }
                    else
                    {
                        <td><input type="button" class="AvailBtn" id="@newIDBtn" /></td>
                    }

                    @Html.HiddenFor(m => m._schedule[6]._timeandRequest[i].timeId)
                    @Html.HiddenFor(m => m._schedule[6]._timeandRequest[i].isMentorAvailable, new { id = newID })

                }
            </tr>
        </table>
    </div>

    <div class="footDiv">
        <div class="commentsDiv">
            <span>About</span>
            @Html.TextAreaFor(r => r.description, new { @class = "commentsArea" })
        </div>
        <div class="reqBtnDiv">
            <input type="submit" value="Update Profile" class="requestButton" />
        </div>
    </div>

}

MentorConnect/MentorConnect/Views/Mentor/Index.cshtml
@model MentorConnect.Models.MentorRequestsModel
@using MentorConnect.Models
@{
    ViewBag.Title = "Index";
    int i = 1;
}

@Scripts.Render("~/bundles/mentorHomeIndex")
@Styles.Render("~/Content/MentorHome")
<div id="mtabs">
    <div class="headDiv">
        <ul>
            <li>
                <a href="#resDiv">All Requests</a>
            </li>
            <li>
                <a href="#mshipListDiv" onclick="DisplayAllMentorShips()">Your Mentorships</a>
            </li>
            <li>
                <a href="#ManageAccount" onclick="DisplayManageAccount()">Manage Account</a>
            </li>
            <li>
                <a href="#EditProfile" onclick="DisplayEditProfile()">Edit Profile</a>
            </li>
        </ul>
    </div>
    <div class="resDiv" id="resDiv">
        <span class="titleLabelReq">All Requests</span>
        <table class="schRequestTable">
            <tr><th class="schReqTh">ID</th><th class="schReqTh">Student</th><th class="schReqTh">Subject Requested</th><th class="schReqTh">Request</th></tr>
            @foreach (MentorshipRequest eRequest in Model._allrequests)
            {
                <tr><td class="schReqTh">@i</td><td class="schReqTh">@eRequest.stuname</td><td class="schReqTh">@eRequest.subject_name</td><td class="schReqTh"><a href="#" onclick="DisplayFullScheduleRequest(@eRequest.mentorshipID)">Click to view the request</a></td></tr>
                i++;
            }
        </table>
    </div>
    <div id="mshipListDiv">

    </div>
    <div id="ManageAccount">

    </div>
    <div id="EditProfile">

    </div>
</div>
<div id="SchReq" title="Student Request">

</div>

            